language: java

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

env:
  - MILL_VERSION=0.3.6
  - MILL_VERSION=0.3.6
    TEST_MILL_VERSION=0.3.6-25-b553df

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/${MILL_VERSION}/${MILL_VERSION} && chmod +x ~/bin/mill
  - mill -i version
  - mill -i test
