= mill-avrohugger - Build avro Bundles with mill
:mill-min-version: 0.3.6
:avrohugger-version: 1.0.0-RC15
:mill-avrohugger-version: 0.0.1
:toc:
:toc-placement: preamble

Module to convert avro schemas to scala classes with the https://github.com/lihaoyi/mill[mill build tool]

== Quickstart

.File: `build.sc`
[source,scala,subs="verbatim,attributes"]
----
// build.sc default imports
import mill._, mill.scalalib._
// This import the mill-avrohugger plugin
import $ivy.`com.chmist::com.chmist.mill.avrohugger:{mill-avrohugger-version}`
import com.chmist.mill.avrohugger._

object project extends ScalaModule with AvroHuggerModule {
   def scalaVersion = "2.12.7"
}
----

Use mill {mill-min-version} or newer, to build the avro bundle.

----
$ mill project.compileAvro
project.compileAvro
Input files to compile:
  project/avro/tutorial/Person.avsc
----

== Configuration

To convert avro schemas, your module has to implement link:core/src/com/chmist/mill/avro/AvroModule.scala[`com.chmist.mill.avro.AvroModule`].

.Configuration options
* `def avroHuggerVersion: T[String]` -
  The avrohugger version. By default it is {avrohugger-version}

* `def avroSources: Sources` -
  The source folder for avro schemas.


== License

Apache License, version 2

== Version Compatibility Matrix

Mill is still in active development, and has no stable API yet.
Hence, not all mill-avrohugger versions work with every mill version.

The following table shows a matrix of compatible mill and mill-avrohugger versions.

.Version Compatibility Matrix
[options="header"]
|===
| mill-avrohugger | mill
| 0.0.1 | 0.3.6
|===

== Changelog

=== mill-avrohugger 0.0.1 - 2019-03-08

* Initial early release to gain user feedback

